apiVersion: v1
kind: Service
metadata:
  name: mc-service-{{ .Values.ServerName }}
spec:
  selector:
    app: minecraft-{{ .Values.ServerName }}
  ports:
    - protocol: TCP
      port: 25565
      targetPort: 25565
  type: NodePort 
